name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/codesix:latest


      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user  # EC2 인스턴스 기본 사용자
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # 1. 실행 중인 Docker 컨테이너 중지 및 삭제
            echo "Stopping and removing existing containers..."
            docker ps -q | xargs -r docker stop
            docker ps -aq | xargs -r docker rm

            # 2. 기존 Docker 이미지를 삭제
            echo "Removing old Docker images..."
            docker images -q | xargs -r docker rmi -f

            # 3. 최신화된 이미지 Pull
            echo "Pulling the latest Docker image..."
            docker pull herokim97/codesix:latest

            # 4. 환경 변수 설정 및 컨테이너 실행
            echo "Running the new Docker container..."
            docker run -d \
              --name codesix-app \
              -e URL=jdbc:mysql://mysql:3306/codesix \
              -e DATABASE_USERNAME=${DATABASE_USERNAME} \
              -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
              -e ACCESS_KEY=${ACCESS_KEY} \
              -e SECRET_KEY=${SECRET_KEY} \
              -p 8080:8080 \
              herokim97/codesix:latest